site_name: Gen711 - Fall2016
pages:
- Home: index.md
- Syllabus: Syllabus.md
- AWS: AWS.md
- Getting Started: lab_lessons/unix.md
- Week 2 lab: lab_lessons/Lab1_blast.md
- Week 3 lab: lab_lessons/alignment.md
- Week 4 lab: lab_lessons/trimming.md
